### ISSUE TITLE
Recency formula

### ISSUE THREAD

**Issue by ercbk** [ghuiber/BTYD#1]
I can't find consistent formula for recency. I did find this definition in docs for python package, [btyd](https://github.com/ColtAllen/btyd/blob/main/docs/More%20examples%20and%20recipes.md), "This is equal to the duration between a customer's first purchase and their latest purchase. (Thus if they have made only 1 purchase, the recency is 0.)" Is the same formula that you use or something different? I did look through the code for your `dc.ElogToCbsCbt` and the functions it calls, but I didn't really follow it all that well. I was hoping you could give me something more straightforward.  
Thanks

**Comment by ghuiber** [comment]
I don't know anything about the Python btyd package. In the R BTYD package recency is just what your intuition would suggest it is: the date of the latest observed transaction. See the first paragraph of section 3.1 in the vignette. There's no formula.
