### ISSUE TITLE
Parameter estimation problem

### ISSUE THREAD

**Issue by Ruonan2021** [ghuiber/BTYD#2]
Hi there,
I got problem when running

```
data(cdnowSummary)
cal.cbs.try <- cdnowSummary$cbs
params <- pnbd.EstimateParameters(cal.cbs = cal.cbs.try, hardie = allHardie)

```
Error message is:

Error in optimx.check(par, optcfg$ufn, optcfg$ugr, optcfg$uhess, lower,  : 
  Cannot evaluate function at initial parameters

How can I solve this problem?

Thanks,
Ruonan

**Comment by jonsch1** [comment]
Check if allHardie is defined: allHardie <- TRUE or allHardie <- FALSE
